#!/usr/bin/env python3

from doubly_connected_list import DoublyLinkedList


test_list = DoublyLinkedList()

#  print(test_list.get_head())
print('add first 0')
test_list.add_first(0)
print('get head')
print(test_list.get_head())
print('get tail')
print(test_list.get_tail())
print('')
print('add first *a')
test_list.add_first('*a')
print('get head')
print(test_list.get_head())
print('get tail')
print(test_list.get_tail())
print('')
print('add last a')
test_list.add_last('a')
print('get head')
print(test_list.get_head())
print('get tail')
print(test_list.get_tail())
print('')
#  print('get value of first')
#  print(test_list.get_first())
#  print('get value of last')
#  print(test_list.get_last())
#  print(test_list.get_tail())
#  print(test_list._current_len)
print('add first *b')
test_list.add_first('*b')
print('get head')
print(test_list.get_head())
print('get tail')
print(test_list.get_tail())
print('')
print('add last b')
test_list.add_last('b')
print('get head')
print(test_list.get_head())
print('get tail')
print(test_list.get_tail())
print('')
print('remove/print last')
print(test_list.remove_last())
print('get head')
print(test_list.get_head())
print('get tail')
print(test_list.get_tail())
print('')
print('remove/print first')
print(test_list.remove_first())
print('get head')
print(test_list.get_head())
print('get tail')
print(test_list.get_tail())
print('')
print('remove/print last')
print(test_list.remove_last())
print('get head')
print(test_list.get_head())
print('get tail')
print(test_list.get_tail())
print('')
print('remove/print first')
print(test_list.remove_first())
print('get head')
print(test_list.get_head())
print('get tail')
print(test_list.get_tail())
print('')
print('remove/print first')
print(test_list.remove_first())
print('get head')
print(test_list.get_head())
print('get tail')
print(test_list.get_tail())
